### ISSUE TITLE
523 passing, 13 test failed

### ISSUE THREAD

**Issue by mreis1** [Path-Check/dcc-sdk.js#7]
Just playing around with the sdk. 
Tried to run tests and got the following: 

Env details: 
OpenSSL 1.1.1k  25 Mar 2021
Node v10.20.1

```
  13 failing
 
  1) CH
       should verify CH_2DCode_raw_1:
     AssertionError: expected undefined not to be undefined
      at Context.it (test/CH.spec.js:8:33)
      at process._tickCallback (internal/process/next_tick.js:68:7)
 
  2) CH
       should verify CH_2DCode_raw_3:
     AssertionError: expected undefined not to be undefined
      at Context.it (test/CH.spec.js:16:33)
      at process._tickCallback (internal/process/next_tick.js:68:7)
 
  3) ES
       should verify ES_2DCode_raw_1002:
     AssertionError: expected undefined not to be undefined
      at Context.it (test/ES.spec.js:31:33)
      at process._tickCallback (internal/process/next_tick.js:68:7)
 
  4) ES
       should verify ES_2DCode_raw_1003:
     AssertionError: expected undefined not to be undefined
      at Context.it (test/ES.spec.js:84:33)
      at process._tickCallback (internal/process/next_tick.js:68:7)
 
  5) ES
       should verify ES_2DCode_raw_1001:
     AssertionError: expected undefined not to be undefined
      at Context.it (test/ES.spec.js:129:33)
      at process._tickCallback (internal/process/next_tick.js:68:7)
 
  6) IS
       should verify IS_2DCode_raw_3:
     AssertionError: expected undefined not to be undefined
      at Context.it (test/IS.spec.js:24:33)
      at process._tickCallback (internal/process/next_tick.js:68:7)
 
  7) IS
       should verify IS_2DCode_raw_4:
     AssertionError: expected undefined not to be undefined
      at Context.it (test/IS.spec.js:32:33)
      at process._tickCallback (internal/process/next_tick.js:68:7)
 
  8) IS
       should verify IS_2DCode_raw_5:
     AssertionError: expected undefined not to be undefined
      at Context.it (test/IS.spec.js:40:33)
      at process._tickCallback (internal/process/next_tick.js:68:7)
 
  9) LT
       should verify LT_2DCode_raw_1:
     AssertionError: expected undefined not to be undefined
      at Context.it (test/LT.spec.js:8:33)
      at process._tickCallback (internal/process/next_tick.js:68:7)
 
  10) LT
       should verify LT_2DCode_raw_2:
     AssertionError: expected undefined not to be undefined
      at Context.it (test/LT.spec.js:16:33)
      at process._tickCallback (internal/process/next_tick.js:68:7)
 
  11) LT
       should verify LT_2DCode_raw_3:
     AssertionError: expected undefined not to be undefined
      at Context.it (test/LT.spec.js:24:33)
      at process._tickCallback (internal/process/next_tick.js:68:7)
 
  12) common
       should verify common_2DCode_raw_CO2:
     AssertionError: expected undefined not to be undefined
      at Context.it (test/common.spec.js:23:33)
      at process._tickCallback (internal/process/next_tick.js:68:7)
 
  13) common
       should verify common_2DCode_raw_CO1:
     AssertionError: expected undefined not to be undefined
      at Context.it (test/common.spec.js:155:33)
      at process._tickCallback (internal/process/next_tick.js:68:7)
 
```

**Comment by vitorpamplona** [comment]
Looks like something to do with the older version of Node. Running on Node 16 works fine. I will do some more research into node versions
